name: github pages

on:
  push:
    branches:
    - main
  schedule:
    # Always regenerate once every 4 hour
    - cron:  '15 */4 * * *'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Timestamp Begin
      run: date

    - uses: actions/checkout@v1

    - name: Install doxygen
      run: sudo apt-get install doxygen graphviz

    - name: Clone LLVM repo
      uses: actions/checkout@v2
      with:
        repository: llvm/llvm-project
        ref: 'main'
        path: 'llvm_src'

    - name: Build MLIR Dialect docs & doxygen src
      run: (mkdir llvm_src/build &&
            cd llvm_src/build &&
            cmake ../llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="host" -DMLIR_INCLUDE_DOCS="true" -DLLVM_ENABLE_DOXYGEN="true" &&
            make -j$(nproc) mlir-doc doxygen-mlir)

    - name: Install MLIR Dialect docs
      run:  ./copy_docs.sh llvm_src/build/tools/mlir/docs/ website/content/docs/

    - name: Install MLIR Source docs
      run:  ./copy_docs.sh llvm_src/mlir/docs/ website/content/docs/ &&
            ./process_included_docs.sh website/content/docs/ &&
            echo "Hack around file/directory name conflict" && rm -Rf website/content/docs/Interfaces &&
            mkdir -p website/content/includes/ &&
            cp -rv llvm_src/mlir/docs/includes/img website/content/includes/

    - name: Install doxygen docs
      run:  cp -r llvm_src/build/tools/mlir/docs/doxygen/html website/static/doxygen

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.80.0'
        # extended: true

    - name: Build Website
      run: (cd website && hugo --minify -d ../public &&
            echo -n mlir.llvm.org > ../public/CNAME )

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./public
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'

    - name: Timestamp End
      run: date
