baseURL = "https://mlir.llvm.org/"
languageCode = "en-us"
title = "MLIR"
theme = "mlir"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

disablePathToLower = true

[Params]

    # Souce Code repository section
    description = "Multi-Level IR Compiler Framework"
    # Update menubar link too.
    # TODO(jpienaar): Find a way that doesn't duplicate it or
    # require redirect.
    github_repository = "https://github.com/llvm/llvm-project/tree/main/mlir"
    version = ""

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/llvm/mlir-www/"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Theme settings section
    # Theme color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts"
    ]

# Global menu section
[[menu.main]]
    name = "Community"
    weight = 3

[[menu.main]]
    name = "Forums"
    parent = "Community"
    url = "https://llvm.discourse.group/c/mlir/31"
    weight = 2

[[menu.main]]
    name = "Chat"
    parent = "Community"
    url = "https://discord.gg/xS7Z362"
    weight = 3

[[menu.main]]
    name = "Source"
    weight = 10
    url = "https://github.com/llvm/llvm-project/tree/main/mlir"

[[menu.main]]
    name = "GitHub"
    parent = "Source"
    weight = 2
    url = "https://github.com/llvm/llvm-project/tree/main/mlir"

[[menu.main]]
    name = "Doxygen"
    parent = "Source"
    weight = 1
    url = "/doxygen/"

[[menu.main]]
    name = "Bugs"
    weight = 20
    url = "https://bugs.llvm.org/buglist.cgi?bug_status=__open__&list_id=177877&order=changeddate%20DESC%2Cpriority%2Cbug_severity&product=MLIR&query_format=specific"

[[menu.main]]
    name = "Logo Assets"
    weight = 40
    url = "https://github.com/llvm/mlir-www/tree/main/website/static/LogoAssets"

[[menu.main]]
    name = "Youtube Channel"
    weight = 60
    url = "https://www.youtube.com/MLIRCompiler"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
